bookcatalog/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='/catalog/', permanent=True)),
    path('catalog/', include('catalog.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

catalog/urls.py
from django.urls import path, re_path
from . import views

app_name = 'catalog'
urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='books'),
    re_path(
        r'^book/(?P<pk>\d+)$',
        views.BookDetailView.as_view(),
        name='book-detail',
    ),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    re_path(
        r'^author/(?P<pk>\d+)$',
        views.AuthorDetailView.as_view(),
        name='author-detail',
    ),
]

catalog/models.py
import uuid
from django.db import models
from django.urls import reverse


class Genre(models.Model):
    """Model representing a book genre."""

    name = models.CharField(
        max_length=200,
        help_text='Enter a book genre (e.g. Science Fiction)',
    )

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.name}'


class Language(models.Model):
    """Model representing a language."""

    name = models.CharField(
        max_length=200,
        help_text=("Enter the book's natural language "
                   "(e.g. English, French, Japanese etc.)"),
    )

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.name}'


class Book(models.Model):
    """Model representing a book.
    Not a specific copy of a book
    """

    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    summary = models.TextField(
        max_length=1000,
        help_text='Enter a brief description of the book',
    )
    isbn = models.CharField(
        'ISBN',
        max_length=13,
        help_text=('13 Character <a href="https://www.isbn-'
                   'international.org/content/what-isbn">ISBN number</a>'),
    )
    genre = models.ManyToManyField(
        Genre,
        help_text='Select a genre for this book',
    )
    language = models.ForeignKey(
        'Language',
        on_delete=models.SET_NULL,
        null=True,
    )

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.title}'

    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        return reverse('catalog:book-detail', args=[str(self.id)])

    def display_genre(self):
        """Create a string for the Genre.
        This is required to display genre in Admin.
        """
        return f', '.join(genre.name for genre in self.genre.all()[:3])

    display_genre.short_description = 'Genre'


class BookInstance(models.Model):
    """Model representing a specific copy of a book.
    It can be borrowed from the library
    """

    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        help_text=('Unique ID for this particular book across '
                   'the whole library'),
    )
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m',
        help_text='Book availability',
    )

    class Meta:
        """Class Meta to order objects when they are returned in a query."""

        ordering = ['due_back']

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.id} ({self.book.title})'


class Author(models.Model):
    """Model representing an author."""

    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    class Meta:
        """Class Meta to order objects when they are returned in a query."""

        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        """Returns the url to access a particular author instance."""
        return reverse('catalog:author-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.last_name}, {self.first_name}'

catalog/views.py
from django.shortcuts import render
from django.views import generic
from catalog.models import Author, Book, BookInstance, Genre


def index(request):
    """View function for home page of site."""
    # Generate counts of some of the main objects
    number_of_books = Book.objects.all().count()
    number_of_book_instances = BookInstance.objects.all().count()
    # Available books (status = 'a')
    number_of_book_instances_available = BookInstance.objects.filter(
        status__exact='a').count()
    # The 'all()' is implied by default
    number_of_authors = Author.objects.count()
    number_of_genres = Genre.objects.count()
    books_match_word = Book.objects.filter(title__contains='the').count()
    # Number of visits to this view, as counted in the session variable
    number_of_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = number_of_visits + 1
    context = {
        'books_count': number_of_books,
        'instances_count': number_of_book_instances,
        'instances_available_count': number_of_book_instances_available,
        'authors_count': number_of_authors,
        'genres_count': number_of_genres,
        'books_word_match_count': books_match_word,
        'visits_count': number_of_visits,
    }
    # Render the html template index.html with the data in the context variable
    return render(request, 'catalog/index.html', context=context)


class BookListView(generic.ListView):
    """View class for books page of site."""

    model = Book
    context_object_name = 'book_list'
    queryset = Book.objects.filter(title__icontains='the')[:5]
    paginate_by = 10


class BookDetailView(generic.DetailView):
    """View class for book detail page of site."""

    model = Book


class AuthorListView(generic.ListView):
    """View class for authors page of site."""

    model = Author
    context_object_name = 'author_list'
    queryset = Author.objects.all()
    paginate_by = 5


class AuthorDetailView(generic.DetailView):
    """View class for auhtor detail page of site."""

    model = Author

catalog/templates/catalog/author_detail.html
{% extends "catalog/base.html" %}

{% block title %}{{ block.super }} | {{ author }}{% endblock %}

{% block content %}
  <h1 class="section double-padded">
    <small>Author Detail</small>
    Full Name: {{ author }}
  </h1>

  <div class="section">
    <p>
      <strong>First name:</strong> {{ author.first_name }}
    </p>

    <p>
      <strong>Last name:</strong> {{ author.last_name }}
    </p>

    <p>
      <strong>Born:</strong> {{ author.date_of_birth }}
    </p>

    <p>
      <strong>Died:</strong> {{ author.date_of_death }}
    </p>
  </div>

  <h3 class="section double-padded">Books</h3>

  <div class="section">
    {% for book in author.book_set.all %}
      <a href="{{ book.get_absolute_url }}">{{ book }}</a> ({{ book.bookinstance_set.all.count }})

      <p>{{ book.summary }}</p>

      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
  </div>
{% endblock %}

catalog/templates/catalog/author_list.html
{% extends "catalog/base.html" %}

{% block title %}{{ block.super }} | Author List{% endblock %}

{% block content %}
  <h1 class="section double-padded">Author List</h1>

  <div class="section">
    <p>Display all authors in Local Library.</p>

    {% if author_list %}
      <ul>
        {% for author in author_list %}
          <li>
            <a href="{{ author.get_absolute_url }}">{{ author }}</a>
          </li>
        {% endfor %}
      </ul>
    {% else %}
      <p>There are no authors available.</p>
    {% endif %}
  </div>
{% endblock %}

catalog/templates/catalog/base.html
<!doctype html>
<html class="no-js" lang="{{ LANGUAGE_CODE }}">
<head>
  <meta charset="utf-8">
  <title>{% block title %}Local Library{% endblock %}</title>
  <meta name="description" content="MDN Django Tutorial - LocalLibrary">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link rel="manifest" href="site.webmanifest">
  <link rel="apple-touch-icon" href="icon.png">
  <!-- Place favicon.ico in the root directory -->

  <link rel="stylesheet" href="https://gitcdn.link/repo/Chalarangelo/mini.css/master/dist/mini-dark.min.css">
  {% load static %}
  <link rel="stylesheet" href="{% static 'catalog/css/main.css' %}">

  <meta name="theme-color" content="#fafafa">
</head>

<body>
  <header class="row">
    <a class="logo col-sm-4" href="https://github.com/biobot-01/book-catalog">Book Catalog</a>
  </header>

  <div class="row">
    <aside class="col-sm-12 col-md-3 col-lg-2">
      {% block sidebar %}
        <nav>
          <a href="{% url 'catalog:index' %}">Home</a>
          <a href="{% url 'catalog:books' %}">All books</a>
          <a href="{% url 'catalog:authors' %}">All authors</a>
        </nav>
      {% endblock %}
    </aside>

    <main class="col-sm-12 col-md-9 col-lg-10">
      <article class="card fluid">
        {% block content %}{% endblock %}

        {% block pagination %}
          {% if is_paginated %}
            <div class="row">
              <div class="col-sm-12 col-md-8 col-md-offset-1">
                {% if page_obj.has_previous %}
                  <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}

                <span>Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</span>

                {% if page_obj.has_next %}
                  <a href="{{ request.path }}?page={{ page_obj.next_page_number}}">next</a>
                {% endif %}
              </div>
            </div>
          {% endif %}
        {% endblock %}
      </article>
    </main>
  </div>

  <footer class="row">
    <span class="col-sm-12 col-md-4 col-lg-3">MDN Django Tutorial - LocalLibrary</span>
    <a class="col-sm-12 col-md-2 col-lg-1" href="https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Tutorial_local_library_website">Go to tutorial</a>
  </footer>
</body>
</html>

catalog/templates/catalog/book_detail.html
{% extends "catalog/base.html" %}

{% block title %}{{ block.super }} | {{ book.title }}{% endblock %}

{% block content %}
  <h1 class="section double-padded">
    <small>Book Detail</small>
    Title: {{ book.title }}
  </h1>

  <div class="section">
    <p>
      <strong>Author:</strong> <a href="{{ book.author.get_absolute_url }}">{{ book.author }}</a>
    </p>

    <p>
      <strong>Summary:</strong> {{ book.summary }}
    </p>

    <p>
      <strong>ISBN:</strong> {{ book.isbn }}
    </p>

    <p>
      <strong>Language:</strong> {{ book.language }}
    </p>

    <p>
      <strong>Genre:</strong>
      {% for genre in book.genre.all %}
        {{ genre }}
        {% if not forloop.last %}, {% endif %}
      {% endfor %}
    </p>
  </div>

  <h3 class="section double-padded">Copies</h3>

  <div class="section">
    {% for copy in book.bookinstance_set.all %}
      <p>{{ copy.get_status_display }}</p>

      {% if copy.status != 'a' %}
        <p>
          <strong>Due to be returned:</strong> {{ copy.due_back }}
        </p>
      {% endif %}

      <p>
        <strong>Imprint:</strong> {{ copy.imprint }}
      </p>

      <p>
        <strong>Id:</strong> {{ copy.id }}
      </p>

      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
  </div>
{% endblock %}

catalog/templates/catalog/book_list.html
{% extends "catalog/base.html" %}

{% block title %}{{ block.super }} | Book List{% endblock %}

{% block content %}
  <h1 class="section double-padded">Book List</h1>

  <div class="section">
    <p>Display 5 books containing the title &#34;the&#34;</p>

    {% if book_list %}
      <ul>
        {% for book in book_list %}
          <li>
            <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{ book.author }})
          </li>
        {% endfor %}
      </ul>
    {% else %}
      <p>There are no books in the library.</p>
    {% endif %}
  </div>
{% endblock %}

catalog/templates/catalog/index.html
{% extends "catalog/base.html" %}

{% block title %}{{ block.super }} | Home{% endblock %}

{% block content %}
  <h1 class="section double-padded">
    <small>Welcome to</small> LocalLibrary
  </h1>

  <div class="section">
    <p>The library has the following record counts:</p>
    <ul>
      <li>
        <strong>Books:</strong> {{ books_count }}
      </li>
      <li>
        <strong>Copies:</strong> {{ instances_count }}
      </li>
      <li>
        <strong>Copies available:</strong> {{ instances_available_count }}
      </li>
      <li>
        <strong>Authors:</strong> {{ authors_count }}
      </li>
      <li>
        <strong>Genres:</strong> {{ genres_count }}
      </li>
      <li>
        <strong>Books with the word "the":</strong> {{ books_word_match_count }}
      </li>
    </ul>

    <p>You have visited this page {{ visits_count }} {% if visits_count == 1 %}time{% else %}times{% endif %}.</p>
  </div>
{% endblock %}